In [1]:
!pip3 install --upgrade pip
!pip3 install pandas
!pip3 install numpy
!pip3 install spotipy
# !pip3 install pprint
!pip3 install requests
# !pip install -r "requirements.txt"

# spotify_history

Requirement already satisfied: pip in ./spotify_sync_env3/lib/python3.8/site-packages (20.3.3)
Requirement already satisfied: pandas in ./spotify_sync_env3/lib/python3.8/site-packages (1.1.3)
Requirement already satisfied: numpy>=1.15.4 in ./spotify_sync_env3/lib/python3.8/site-packages (from pandas) (1.19.2)
Requirement already satisfied: pytz>=2017.2 in ./spotify_sync_env3/lib/python3.8/site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in ./spotify_sync_env3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in ./spotify_sync_env3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: numpy in ./spotify_sync_env3/lib/python3.8/site-packages (1.19.2)
Requirement already satisfied: spotipy in ./spotify_sync_env3/lib/python3.8/site-packages (2.16.1)
Requirement already satisfied: six>=1.10.0 in ./spotify_sync_env3/lib/python3.8/site-packages (from spotipy) (1.15.0)
Requirement already satisfied: requests>=2.20.0 in ./spotify_sync_env3/lib/python3.8/site-packages (from spotipy) (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests>=2.20.0->spotipy) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests>=2.20.0->spotipy) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests>=2.20.0->spotipy) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests>=2.20.0->spotipy) (3.0.4)
Requirement already satisfied: requests in ./spotify_sync_env3/lib/python3.8/site-packages (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./spotify_sync_env3/lib/python3.8/site-packages (from requests) (1.25.11)

In [2]:
import sys
sys.executable

'/Users/akuna/preps/spotify_sync/spotify_sync_env3/bin/python3'

In [3]:
import pandas as pd
import numpy as np
import pytz 
import spotipy
import spotipy.util as util
import pprint
import requests

from datetime import datetime, timedelta

time per day
time of day
most listened to all time, this year, this month
haven't listened to recently, but a favorite
haven't listened in a long time ( low play count
most popular artists

In [4]:
header_names = ["artist", "album", "song", "date_played"]
spotify_history = pd.read_csv("awlego.csv", header=None, names=header_names)

In [4]:
# AUTOGENERATED_PLAYLISTS = {
#     'MOST_LISTENED_TO': {
#         'id': '7sAPf6VkEDnCamqOtY5HfK'
#         'calc_func': 
#     },
#     'MOST_LISTENED_TO_ID': '7sAPf6VkEDnCamqOtY5HfK',
#     'RECENT_FAVORITES_ID': "0fxWRM70Cu7lXHj3eXOfds",
#     'BINGED_SONGS_ID': '2Lgk5s5DsuhilEBdQoUbjo',
# }

In [5]:
MOST_LISTENED_TO_ID = '7sAPf6VkEDnCamqOtY5HfK'
RECENT_FAVORITES_ID = "0fxWRM70Cu7lXHj3eXOfds"
BINGED_SONGS_ID = '0A15ZxmJfLvcJThvPOOWBh'

In [6]:
# Application name	Scrobble to CSV
# API key	e8db1a5e26f01ca1abae47d64738e9b4
# Shared secret	06be12c48353f39511ac0b6eb6fdb82e
# Registered to	awlego

In [6]:
spotify_history['date_played'] = pd.to_datetime(spotify_history['date_played'], utc=True, infer_datetime_format=True)
spotify_history = spotify_history.dropna()

In [7]:
spotify_history

,artist,album,song,date_played
0,Taylor Swift,evermore,gold rush,2020-12-23 00:29:00+00:00
1,Taylor Swift,evermore,champagne problems,2020-12-23 00:20:00+00:00
2,Taylor Swift,evermore,willow,2020-12-23 00:17:00+00:00
3,Andrew Belle,Dive Deep,When the End Comes,2020-12-23 00:10:00+00:00
4,The Oh Hellos,Dear Wormwood,Soldier Poet King,2020-12-23 00:08:00+00:00
...,...,...,...,...
24656,A Tribe Called Quest,The Love Movement,Find a Way,2019-03-20 01:40:00+00:00
24657,A Tribe Called Quest,Midnight Marauders,Award Tour,2019-03-20 01:36:00+00:00
24658,A Tribe Called Quest,The Anthology,Electric Relaxation,2019-03-20 01:33:00+00:00
24659,A Tribe Called Quest,People's Instinctive Travels and the Paths of ...,Can I Kick It?,2019-03-20 01:28:00+00:00
24660,Canyon City,Paper Airplanes,Paper Airplanes,2019-03-20 01:18:00+00:00

In [11]:
def calc_play_counts(history):
    play_counts_df =  history.groupby(["artist", "album", "song"]).size().rename('play_count').reset_index().sort_values('play_count', ascending=False)
    return play_counts_df

calc_play_counts(spotify_history)

,artist,album,song,play_count
4995,Penny and Sparrow,Don't Wanna Be Without Ya,Don't Wanna Be Without Ya,108
853,Bon Iver,U (Man Like),U (Man Like),84
1810,Ed Sheeran,No.6 Collaborations Project,Remember the Name (feat. Eminem & 50 Cent),71
1811,Ed Sheeran,No.6 Collaborations Project,South of the Border (feat. Camila Cabello & Ca...,69
2986,Jon Bellion,Glory Sound Prep,Cautionary Tales,68
...,...,...,...,...
3270,Justin Bieber,My World 2.0,Stuck in the Moment,1
3268,Justin Bieber,Journals,Confident,1
3266,Justin Bieber,Holy,Holy (feat. Chance the Rapper),1
3248,Jump Little Children,Between The Dim And The Dark,Young America,1
7830,현아,A Talk,빨개요,1

In [12]:
def get_most_played_artists(spotify_history):
    play_counts_df = calc_play_counts(spotify_history)
    return play_counts_df.groupby('artist').sum().sort_values('play_count', ascending=False)

get_most_played_artists(spotify_history)

                   play_count
artist
Bon Iver                 1016
Taylor Swift              931
The Oh Hellos             838
Jon Bellion               716
Penny and Sparrow         694
...                       ...
Joshua Bassett              1
Josh White                  1
Josh Gilligan               1
Joseph Kerschbaum           1
현아                          1

[2255 rows x 1 columns]

In [13]:
def calc_most_listened_all_time(history, limit=50):
    counts = calc_play_counts(history)
    return counts.iloc[0:limit]
    

# calc_most_listened_all_time(spotify_history)

In [14]:
def calc_recent_favorites(history, limit=50, time_frame_days=30):
    time_frame = datetime.now(pytz.utc) - timedelta(days=time_frame_days)
    history = history.loc[history['date_played'] > time_frame]
    counts = calc_play_counts(history)
    return counts.iloc[0:limit]
    
calc_recent_favorites(spotify_history, limit=25, time_frame_days=150)

,artist,album,song,play_count
1562,Taylor Swift,folklore,exile (feat. Bon Iver),59
1569,Taylor Swift,folklore,peace,58
1568,Taylor Swift,folklore,my tears ricochet,24
1572,Taylor Swift,folklore,the last great american dynasty,22
224,Bon Iver,AUATC,AUATC,22
1566,Taylor Swift,folklore,mad woman,21
1565,Taylor Swift,folklore,invisible string,21
1558,Taylor Swift,folklore,august,21
1559,Taylor Swift,folklore,betty,20
1733,The Oh Hellos,The Oh Hellos EP,Hello My Old Heart,20
1591,Tessa Violet,Bad Ideas,Crush,19
1573,Taylor Swift,folklore,this is me trying,19
1560,Taylor Swift,folklore,cardigan,19
1563,Taylor Swift,folklore,hoax,19
1571,Taylor Swift,folklore,the 1,18
1229,Penny and Sparrow,Finch,Don't Wanna Be Without Ya,18
1570,Taylor Swift,folklore,seven,18
1561,Taylor Swift,folklore,epiphany,18
1594,Tessa Violet,Bad Ideas,I Like (the idea of) You,18
1564,Taylor Swift,folklore,illicit affairs,18
1567,Taylor Swift,folklore,mirrorball,17
1724,The Oh Hellos,Notos,Constellations,17
245,Bon Iver,ii,U (Man Like),16
1589,Tessa Violet,Bad Ideas,Bad Ideas,15
822,K/DA,POP/STARS,POP/STARS,14

In [11]:
# Spotify Web API
%env SPOTIPY_CLIENT_ID=e04e8a864b5c45a2b4ed25907bcf3202
%env SPOTIPY_CLIENT_SECRET=d919de50cb014dd28f3569b63cab104a
%env SPOTIPY_REDIRECT_URI=http://localhost:6006

# sp = spotipy.Spotify()

# scope = 'user-library-read'

# username = 'awlego'

# token = util.prompt_for_user_token(username, scope)

# if token:
#     sp = spotipy.Spotify(auth=token)
#     results = sp.current_user_saved_tracks()
#     for item in results['items']:
#         track = item['track']
#         print(track['name'] + ' - ' + track['artists'][0]['name'])
# else:
#     print("Can't get token for", username)

env: SPOTIPY_CLIENT_ID=e04e8a864b5c45a2b4ed25907bcf3202
env: SPOTIPY_CLIENT_SECRET=d919de50cb014dd28f3569b63cab104a
env: SPOTIPY_REDIRECT_URI=http://localhost:6006

In [16]:

def make_playlist(username, token, playlist_name, playlist_description):
    if token:
        sp = spotipy.Spotify(auth=token)
        sp.trace = False
        playlists = sp.user_playlist_create(username, playlist_name,
                                            playlist_description)
    else:
        print("Can't get token for", username)
    return playlists


def playlist_replace_tracks(username, token, playlist_id, tracks):
    if token:
        sp = spotipy.Spotify(auth=token)
        sp.trace = True
        playlists = sp.user_playlist_replace_tracks(username, playlist_id, tracks)
    else:
        print("Can't get token for", username)
    return playlists


def lookup_track(artist, album, song, token):
    sp = spotipy.Spotify(auth=token)
    probable_song_name = song
#     probable_song_name = song.split("feat.")[0]
#     print(song)
    search_result = sp.search(f'{probable_song_name} {artist} {album}')
#     pprint.pprint(search_result)
    try:
        result = search_result['tracks']['items'][0]['id']
    except (KeyError, IndexError):
        result = None
        pass
    return result

    
def make_recent_favorites(username, token):
    recent_favs = calc_recent_favorites(spotify_history, limit=25, time_frame_days=30)
#     print(recent_favs)
    recent_favs['spotify_id'] = recent_favs.apply(lambda x: lookup_track(x['artist'], x['album'], x['song'], token), axis=1)
    
    track_ids = recent_favs['spotify_id']
    if token:
        playlist_results = make_playlist(username, token, "Recent Favorites", False)
#         playlist_results = {'id': '4hQXn0GukkTMkks5FNphxc'}
        sp = spotipy.Spotify(auth=token)
        sp.user_playlist_add_tracks(username, playlist_results['id'], track_ids)
    else:
        print("Can't get token for", username)
        
        
def update_recent_favorites(username, token, playlist_id):
    recent_favs = calc_recent_favorites(spotify_history, limit=25, time_frame_days=30)
#     print(recent_favs)
    recent_favs['spotify_id'] = recent_favs.apply(lambda x: lookup_track(x['artist'], x['album'], x['song'], token), axis=1)
    track_ids = recent_favs['spotify_id']
#     print(track_ids)
    track_ids = track_ids.dropna()

    playlist_results = playlist_replace_tracks(username, token, playlist_id, track_ids)


# lookup_track("Daft Punk", "Random Access Memories", "Instant Crush feat. Julian Casablancas", token)
# scope = 'playlist-modify-private'
# username = "awlego"
# token = util.prompt_for_user_token(username, scope)
# make_playlist(username, token, "my_api_playlist", False)
# make_recent_favorites(username, token)
# update_recent_favorites(username, token, RECENT_FAVORITES_ID)

In [15]:
# make my most listened to playlist and print it so I can get the ID
# print(make_playlist(username, token, "Most Listened To", False))

In [16]:
# def update_recently_played(username, token, playlist_id):

In [17]:
calc_recent_favorites(spotify_history, limit=25, time_frame_days=30)

,artist,album,song,play_count
276,Taylor Swift,evermore,evermore (feat. Bon Iver),9
288,Taylor Swift,folklore,peace,7
209,Penny and Sparrow,Finch,Don't Wanna Be Without Ya,7
301,Tessa Violet,Bad Ideas,I Like (the idea of) You,6
273,Taylor Swift,evermore,coney island (feat. The National),6
131,Kacey Musgraves,Golden Hour,Rainbow,5
274,Taylor Swift,evermore,cowboy like me,5
328,The Oh Hellos,The Oh Hellos EP,Hello My Old Heart,5
286,Taylor Swift,folklore,exile (feat. Bon Iver),5
281,Taylor Swift,evermore,marjorie,5
368,dodie,Human,monster,4
215,Penny and Sparrow,We've Got Something (OurVinyl Sessions),We've Got Something (OurVinyl Sessions),4
298,Tessa Violet,Bad Ideas,Bad Ideas,4
283,Taylor Swift,evermore,tolerate it,4
208,Penny and Sparrow,Finch,Cult Classically,4
279,Taylor Swift,evermore,ivy,4
278,Taylor Swift,evermore,happiness,4
277,Taylor Swift,evermore,gold rush,4
364,dodie,Human,HUMAN,4
52,Bon Iver,ii,U (Man Like),4
51,Bon Iver,ii,RABi,4
67,Caamp,Fall Fall Fall,Fall Fall Fall,4
272,Taylor Swift,evermore,closure,4
271,Taylor Swift,evermore,champagne problems,4
275,Taylor Swift,evermore,dorothea,3

In [18]:
# Only should need to run once:
# make_playlist(username, token, "Binged Songs", False)

In [20]:


def calc_binged_songs(spotify_history):
    spotify_history['day_played'] = spotify_history['date_played'].dt.date
    df =  spotify_history.groupby(["artist", "album", "song", "day_played"]).size().rename('daily_play_count').reset_index().sort_values('daily_play_count', ascending=False)
    df = df.where(df['daily_play_count'] >= 3).dropna()
    df = df.groupby(['artist', 'album', 'song'])['daily_play_count'].sum().rename('summed_top_daily_play_counts').reset_index().sort_values('summed_top_daily_play_counts', ascending=False)
    return df

def update_binged_songs(username, token):
    binged_songs = calc_binged_songs(spotify_history)
    binged_songs['spotify_id'] = binged_songs.apply(lambda x: lookup_track(x['artist'], x['album'], x['song'], token), axis=1)
    track_ids = binged_songs['spotify_id']
    track_ids = track_ids.dropna()
    print(track_ids)
    playlist_results = playlist_replace_tracks(username, token, BINGED_SONGS_ID, binged_songs)
    
calc_binged_songs(spotify_history)
# update_binged_songs(username, token)

,artist,album,song,summed_top_daily_play_counts
87,Penny and Sparrow,Don't Wanna Be Without Ya,Don't Wanna Be Without Ya,43.0
10,Bon Iver,U (Man Like),U (Man Like),33.0
108,Taylor Swift,folklore,exile (feat. Bon Iver),26.0
112,Taylor Swift,folklore,peace,17.0
47,Jhameel,Waves,Pursuit of Glory,14.0
...,...,...,...,...
56,Lauv,i'm so tired...,i'm so tired...,3.0
54,Kanye West,Graduation,Stronger,3.0
53,K/DA,POP/STARS,POP/STARS,3.0
51,Jon Bellion,Glory Sound Prep,Mah's Joint (feat. Quincy Jones),3.0
74,Mike Shinoda,Post Traumatic (Deluxe Version),Prove You Wrong,3.0

In [19]:
def find_standout_songs(spotify_history, timewindow):
    df = calc_play_counts(spotify_history)
    
# find_standout_songs(spotify_history)

In [20]:
def update_most_listened_all_time(username, token, playlist_id):
    most_listened_df = calc_most_listened_all_time(spotify_history)
    most_listened_df['spotify_id'] = most_listened_df.apply(lambda x: lookup_track(x['artist'], x['album'], x['song'], token), axis=1)
    track_ids = most_listened_df['spotify_id']
    track_ids = track_ids.dropna()
    playlist_results = playlist_replace_tracks(username, token, playlist_id, track_ids)
    
# update_most_listened_all_time(username, token, MOST_LISTENED_TO_ID)

In [21]:
def update_playlist(username, token, playlist_id, calc_func):
    df = calc_func(spotify_history)
    df['spotify_id'] = df.apply(lambda x: lookup_track(x['artist'], x['album'], x['song'], token), axis=1)
    track_ids = df['spotify_id']
    track_ids = track_ids.dropna()
    playlist_results = playlist_replace_tracks(username, token, playlist_id, track_ids)

In [22]:
def update_all_playlists(username, token):
#     for key in AUTOGENERATED_PLAYLISTS:
#         update_playlist(username, token, playlist[AUTOGENERATED_PLAYLISTS[key]])
    update_most_listened_all_time(username, token, MOST_LISTENED_TO_ID)
    update_recent_favorites(username, token, RECENT_FAVORITES_ID)
#     update_binged_songs(username, token)

scope = 'playlist-modify-private'
username = "awlego"
token = util.prompt_for_user_token(username, scope)
update_all_playlists(username, token)

In [ ]:
stop

In [ ]:
def recently_played():
    """Calculates the last 50 songs played."""
    pass

In [ ]:
#todo
# combine the multiple versions of songs together and pick the one that I have saved and if not saved then the one that I have more playcounts for.

In [ ]:
requests.get('https://api.github.com')

In [ ]:
data = {
    'method':'user.getrecenttracks',
    'user':username,
    'api_key':'e8db1a5e26f01ca1abae47d64738e9b4',
    'limit':200,
    'page': 1,
}

response = requests.post("https://ws.audioscrobbler.com/2.0/", data=data)
# json_response = response.json()

In [ ]:
response.status_code

In [ ]:
import xml.etree.ElementTree as ET
import json

!pip3 install xmljson
from xmljson import badgerfish as bf

In [21]:
tree = ET.fromstring(response.text)
tree

NameError: name 'ET' is not defined

In [ ]:
temp = json.dumps(bf.data(tree))
df = pd.read_json(temp)

In [ ]:
df

In [ ]:
temp

In [ ]:
scope = 'user-read-recently-played'
token = util.prompt_for_user_token(username, scope)
header = {
   "access_token": token,
   'Authorization': 'Bearer {0}'.format(token),
}
data = {
    'limit': 50
}

# note: songs have to finish for this to catch them.
response = requests.get('https://api.spotify.com/v1/me/player/recently-played',
                        headers=header,
                        params=data)

In [ ]:
print(response.status_code)
for item in response.json()['items']:
    print(item['track']['name'])
#     print(item['track'])

In [14]:
twenty_twenty_history = spotify_history.where(spotify_history['date_played'].dt.year == 2020).dropna()

In [15]:
twenty_twenty_history

,artist,album,song,date_played
0,Taylor Swift,evermore,gold rush,2020-12-23 00:29:00+00:00
1,Taylor Swift,evermore,champagne problems,2020-12-23 00:20:00+00:00
2,Taylor Swift,evermore,willow,2020-12-23 00:17:00+00:00
3,Andrew Belle,Dive Deep,When the End Comes,2020-12-23 00:10:00+00:00
4,The Oh Hellos,Dear Wormwood,Soldier Poet King,2020-12-23 00:08:00+00:00
...,...,...,...,...
13546,B.o.B,B.o.B Presents: The Adventures of Bobby Ray,Nothin' on You (feat. Bruno Mars),2020-01-01 03:29:00+00:00
13547,Ed Sheeran,÷ (Deluxe),Shape of You,2020-01-01 03:25:00+00:00
13548,Ed Sheeran,No.6 Collaborations Project,BLOW (with Chris Stapleton & Bruno Mars),2020-01-01 00:10:00+00:00
13549,Ariana Grande,Dangerous Woman,Let Me Love You,2020-01-01 00:07:00+00:00
13550,Ed Sheeran,+,Kiss Me,2020-01-01 00:02:00+00:00

In [16]:
calc_most_listened_all_time(twenty_twenty_history)

,artist,album,song,play_count
3997,Tessa Violet,Bad Ideas,Crush,65
3966,Taylor Swift,folklore,exile (feat. Bon Iver),59
3973,Taylor Swift,folklore,peace,58
4810,dodie,Human,monster,58
4000,Tessa Violet,Bad Ideas,I Like (the idea of) You,55
4801,dodie,BOYS LIKE YOU,BOYS LIKE YOU,53
1090,Dwayne Johnson,Moana (Original Motion Picture Soundtrack/Delu...,You're Welcome,52
4816,dodie,MOOMINVALLEY (Official Soundtrack),Ready Now,52
4803,dodie,Guiltless,Guiltless,52
565,Bon Iver,ii,RABi,48
3995,Tessa Violet,Bad Ideas,Bad Ideas,47
4805,dodie,Human,HUMAN,47
4611,Vulfpeck,The Beautiful Game,Dean Town,44
2004,Jonas Brothers,What A Man Gotta Do,What A Man Gotta Do,43
4299,The Oh Hellos,The Oh Hellos EP,Hello My Old Heart,43
4819,dodie,You - EP,In The Middle,43
516,Bon Iver,22 A Million,8 (circle),41
568,Bon Iver,ii,U (Man Like),38
1299,FINNEAS,I Lost a Friend,I Lost a Friend,37
4609,Vulfpeck,The Beautiful Game,Animal Spirits,37
3998,Tessa Violet,Bad Ideas,Feelin,37
3159,Penny and Sparrow,Finch,Don't Wanna Be Without Ya,35
511,Bon Iver,22 A Million,22 (OVER S∞∞N),35
4458,Tom Morello,The Atlas Underground,Every Step That I Take (feat. Portugal. The Ma...,34
1005,Daði Freyr,Söngvakeppnin 2020,Think About Things,34
4428,Thin Lizzy,Jailbreak (Deluxe Edition),The Boys Are Back in Town,33
553,Bon Iver,PDLIF,PDLIF,32
561,Bon Iver,ii,Holyfields,32
1427,George Ezra,Staying at Tamara's,Shotgun,31
2778,Mother Mother,Dance And Cry,It's Alright,31
4630,Walk the Moon,Walk The Moon (Expanded Edition),Jenny,30
560,Bon Iver,ii,Hey Ma,29
4507,Twenty One Pilots,Level of Concern,Level of Concern,29
3926,Taylor Swift,Lover,The Man,28
2144,Justin Bieber,Intentions,Intentions,28
4821,dodie,You - EP,Would You Be So Kind,28
3653,Sara Watkins,Young In All The Wrong Ways,One Last Time,28
4229,The Mowgli's,Waiting For The Dawn,San Francisco,27
3542,Ry x,Unfurl,YaYaYa,27
1153,Ed Sheeran,No.6 Collaborations Project,Remember the Name (feat. Eminem & 50 Cent),27
564,Bon Iver,ii,Naeem,26
4631,Walk the Moon,Walk The Moon (Expanded Edition),Next in Line,25
1154,Ed Sheeran,No.6 Collaborations Project,South of the Border (feat. Camila Cabello & Ca...,25
571,Bon Iver,ii,iMi,25
352,Bea Miller,Aurora,outside,25
3972,Taylor Swift,folklore,my tears ricochet,24
1380,Florence + the Machine,Lungs (Deluxe Edition),Dog Days Are Over,24
1950,Jon Bellion,Glory Sound Prep,Stupid Deep,24
3494,Run River North,Drinking From a Salt Pond,29,23
4290,The Oh Hellos,Notos,Constellations,23

In [18]:
get_most_played_artists(twenty_twenty_history)[0:10]

                   play_count
artist
Taylor Swift              661
Bon Iver                  657
dodie                     507
The Oh Hellos             397
Tessa Violet              366
Ed Sheeran                262
Jon Bellion               231
Penny and Sparrow         231
Mat Kearney               218
Run River North           189

In [19]:
get_most_played_artists(spotify_history)[0:10]

                   play_count
artist
Bon Iver                 1016
Taylor Swift              931
The Oh Hellos             838
Jon Bellion               716
Penny and Sparrow         694
dodie                     508
Ed Sheeran                505
Mat Kearney               399
Muse                      373
Tessa Violet              366